// =============================================================================
// cream_positions_test.cpp -- unit tests for context_parallel/CreamPositions.h
// (CREAM / PoSE / RandPos position-label generators). Pure CPU, no CUDA, no
// framework -- same standalone style as cp_rope_deltas_test.cpp.
//
// Build & run (from the CP/ repo root):
//   g++ -std=c++17 -I. Tests/cream_positions_test.cpp -o /tmp/cream_positions_test \
//       && /tmp/cream_positions_test
//
// Golden values are captured from the actual Python reference math
// (/tmp/cream_train.py, regenerated by /tmp/cream_golden.py) so the test
// validates the deterministic transform independent of RNG-stream parity, and
// specifically pins the four cross-language hazards: .astype(int) truncation,
// true rand_factor/2 division, inclusive randint, and np.interp arg order.
// =============================================================================

#include "context_parallel/CreamPositions.h"

#include <cstdio>
#include <cstdint>
#include <set>
#include <vector>

using namespace OwnTensor::cp::cream;

static int g_failures = 0;

static void expect(const char* tag, bool ok) {
  if (!ok) { ++g_failures; std::printf("FAIL %s\n", tag); }
  else       std::printf("ok   %s\n", tag);
}

static int64_t vhash(const std::vector<int64_t>& v) {
  int64_t h = 0;
  for (size_t i = 0; i < v.size(); ++i) h += static_cast<int64_t>(i + 1) * v[i];
  return h;
}

static bool monotonic(const std::vector<int64_t>& v) {
  for (size_t i = 1; i < v.size(); ++i) if (v[i] <= v[i - 1]) return false;
  return true;
}

int main() {
  // ---- (a) Golden math: cream_labels_from_draws vs Python reference ----------
  // Tuples: (T, factor, branch, rand_factor, end_id) -> (len, vhash)
  struct GC { int T, factor, branch, rf; int64_t end_id, len, hash; };
  const GC gcs[] = {
      {256, 8, 0, 8, 700, 256, 44045830},
      {256, 8, 1, 5, 300, 256, 21283296},
      { 96, 2, 0, 4, 120,  96,   630640},
      {300, 4, 1, 6, 900, 300, 38097978},
  };
  for (const auto& g : gcs) {
    auto L = cream_labels_from_draws(g.T, g.factor, g.branch, g.rf, g.end_id);
    char tag[128];
    std::snprintf(tag, sizeof tag, "cream_labels T=%d f=%d b=%d rf=%d eid=%lld",
                  g.T, g.factor, g.branch, g.rf, (long long)g.end_id);
    expect(tag, (int64_t)L.size() == g.len && vhash(L) == g.hash &&
                    monotonic(L) && L.front() == 0 &&
                    L.back() == (int64_t)g.factor * g.T - 1);
  }

  // ---- (b1) rand_factor_from_u vs Python (sigma=3.0) -------------------------
  // (u, factor) -> rand_factor. Catches interp arg-order + .astype(int) trunc.
  struct GR { double u; int factor, rf; };
  const GR grs[] = {
      {0.01, 2, 2}, {0.01, 4, 2}, {0.01, 8, 2},
      {0.25, 2, 2}, {0.25, 4, 2}, {0.25, 8, 6},
      {0.50, 2, 3}, {0.50, 4, 5}, {0.50, 8, 9},
      {0.75, 2, 4}, {0.75, 4, 7}, {0.75, 8, 11},
      {0.99, 2, 4}, {0.99, 4, 8}, {0.99, 8, 15},
  };
  for (const auto& g : grs) {
    int rf = rand_factor_from_u(g.u, g.factor, 3.0);
    char tag[96];
    std::snprintf(tag, sizeof tag, "rand_factor_from_u u=%.2f f=%d -> %d (want %d)",
                  g.u, g.factor, rf, g.rf);
    expect(tag, rf == g.rf);
  }

  // ---- (b2) end_id_range vs Python -- incl. ODD rf (true-division guard) -----
  struct GE { int T, factor, branch, rf; int64_t lo, hi; };
  const GE ges[] = {
      {256, 8, 0, 8, 425, 938},
      {256, 8, 0, 7, 382, 810},   // ODD rf: int-division would give (340,682)
      {256, 8, 1, 5, 509, 607},
      { 96, 2, 0, 4,  94, 159},
      {300, 4, 1, 7, 950, 1033},
  };
  for (const auto& g : ges) {
    auto [lo, hi] = end_id_range(g.T, g.factor, g.branch, g.rf);
    char tag[112];
    std::snprintf(tag, sizeof tag,
                  "end_id_range T=%d f=%d b=%d rf=%d -> (%lld,%lld) want (%lld,%lld)",
                  g.T, g.factor, g.branch, g.rf, (long long)lo, (long long)hi,
                  (long long)g.lo, (long long)g.hi);
    expect(tag, lo == g.lo && hi == g.hi);
  }

  // ---- (c) Structural invariants across both branches ------------------------
  for (int branch = 0; branch <= 1; ++branch) {
    const int T = 256, factor = 8;
    auto L = generate_cream_positions(T, factor, 3.0, /*seed=*/branch == 0 ? 1u : 2u);
    const int ht = cream_head_tail_len(T, factor, branch);
    (void)ht;
    char tag[96];
    std::snprintf(tag, sizeof tag, "cream structural seed branch~%d", branch);
    expect(tag, (int)L.size() == T && monotonic(L) && L.front() == 0 &&
                    L.back() == (int64_t)factor * T - 1);
  }

  // Exact block lengths for BOTH branches via the math layer.
  {
    auto L0 = cream_labels_from_draws(256, 8, 0, 8, 700);  // head=tail=85
    auto L1 = cream_labels_from_draws(256, 8, 1, 8, 700);  // head=tail=32
    // head block is [0..head): count leading contiguous-from-0 entries.
    auto head_len = [](const std::vector<int64_t>& v) {
      int n = 0; while (n < (int)v.size() && v[n] == n) ++n; return n; };
    expect("branch0 head_len==T/3 (85)", head_len(L0) == 85);
    expect("branch1 head_len==4*factor (32)", head_len(L1) == 32);
  }

  // ---- guards throw --------------------------------------------------------
  auto throws = [](auto fn) { try { fn(); return false; } catch (...) { return true; } };
  expect("guard factor<2 throws",
         throws([] { cream_labels_from_draws(256, 1, 0, 2, 100); }));
  expect("guard head+tail>=T throws (tiny T, branch1)",
         throws([] { cream_labels_from_draws(2, 8, 1, 2, 1); }));

  // ---- randint inclusivity: uniform_int_distribution can hit both ends -------
  {
    std::mt19937_64 rng(12345);
    std::uniform_int_distribution<int> d(0, 1);
    bool saw0 = false, saw1 = false;
    for (int i = 0; i < 200 && !(saw0 && saw1); ++i) {
      int v = d(rng); saw0 |= (v == 0); saw1 |= (v == 1);
    }
    expect("randint(0,1) reaches both 0 and 1", saw0 && saw1);
  }

  // ---- PoSE / RandPos: shape + monotonic + range -----------------------------
  {
    auto P = generate_pose_positions(256, 8, /*seed=*/7);
    expect("pose length==T", (int)P.size() == 256);
    expect("pose monotonic", monotonic(P));
    expect("pose in [0,scaled_max)", P.front() >= 0 && P.back() < (int64_t)8 * 256);
    expect("pose starts at 0", P.front() == 0);
  }
  {
    auto R = generate_randpos_positions(256, 8, /*seed=*/7);
    std::set<int64_t> uniq(R.begin(), R.end());
    expect("randpos length==T", (int)R.size() == 256);
    expect("randpos unique", (int)uniq.size() == 256);
    expect("randpos sorted (monotonic)", monotonic(R));
    expect("randpos in [0,scaled_max)", R.front() >= 0 && R.back() < (int64_t)8 * 256);
  }

  if (g_failures == 0) { std::printf("\nALL cream_positions tests passed.\n"); return 0; }
  std::printf("\n%d cream_positions test(s) FAILED.\n", g_failures);
  return 1;
}
